name: Build Hostlists Registry

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: yarn install
        run: yarn install

      - name: node
        run: |
          TLS=insecure node index.js
